/**
 * Scrapper Jorge API
 * The Scrapper API of Jorge
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FeedDto { 
    title: string;
    body: string;
    image: string;
    source: any;
    publisher: string;
}